Update 4-not_found_page_404

diff --git a/web_server/4-not_found_page_404 b/web_server/4-not_found_page_404
--- a/web_server/4-not_found_page_404
+++ b/web_server/4-not_found_page_404
@@ -1,13 +1,12 @@
 #!/usr/bin/env bash
-# Configures a new ubuntu machine by installing
-# Nginx where it should be listening on port 80
-# Serve a page that would return a Hello World string
-#
-# colors
+
+# Colors
 blue='\e[1;34m'
 brown='\e[0;33m'
 green='\e[1;32m'
 reset='\033[0m'
+
+set -e  # Exit on error
 
 echo -e "${blue}Updating and installing ${brown}Nginx${blue}.${reset}\n"
 sudo apt-get update -y -qq && \
@@ -15,10 +14,10 @@ sudo apt-get update -y -qq && \
 
 echo -e "\n${blue}Setting up some minor stuff.${reset}\n"
 
-# starting nginx service
+# Starting nginx service
 sudo service nginx start
 
-# allowing nginx on firewall
+# Allowing nginx on firewall
 sudo ufw allow 'Nginx HTTP'
 
 # Give the user ownership to website files for easy editing
@@ -35,7 +34,7 @@ echo -e "Hello World!" > /var/www/html/index.nginx-debian.html
 sudo sed -i '24i\	rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
 
 # Set up a 404 page
-echo "Ceci n'est pas une page" >> /var/www/html/error_404.html
+echo "Ceci n'est pas une page" > /var/www/html/error_404.html
 sudo sed -i '25i\	error_page 404 /error_404.html;' /etc/nginx/sites-available/default
 
 # Restarting nginx
